export const tools = [
  {
    title: '时间戳转换',
    desc: '时间戳转换工具',
    path: '/timestamp',
    icon: '/timestamp.png',
  },
  {
    title: '二维码生成器',
    desc: '文本/链接生成二维码工具',
    path: '/qrcode',
    icon: '/qrcode.png',
  },
  {
    title: 'URL 编码/解码',
    desc: 'URL 编码/解码工具',
    path: '/url',
    icon: '/url.png',
  },
  {
    title: 'Unicode 编码',
    desc: 'Unicode 编码工具',
    path: '/unicode',
    icon: '/unicode.png',
  },
  {
    title: 'JSON 格式化',
    desc: 'JSON 格式化工具',
    path: '/json',
    icon: '/json.png',
  },
  {
    title: '文件对比',
    desc: '文件对比工具',
    path: '/diff',
    icon: '/diff.png',
  },
  {
    title: '进制转换',
    desc: '进制转换工具',
    path: '/binary',
    icon: '/binary.png',
  },
  {
    title: 'JSON to TS',
    desc: 'JSON 转换成 Typescript 类型工具',
    path: '/ts',
    icon: '/ts.png',
  },
  {
    title: '数字转人民币',
    desc: '数字转人民币工具',
    path: '/rmb',
    icon: '/rmb.png',
  },
  {
    title: '代码着色',
    desc: '代码着色工具',
    path: '/highlight',
    icon: '/highlight.png',
  },
  {
    title: '代码在线运行',
    desc: '代码在线运行工具',
    path: '/code',
    icon: '/code.png',
  },
  {
    title: '代码生成图片',
    desc: '代码生成图片工具',
    path: '/pic',
    icon: '/pic.png',
  },
  {
    title: '颜色选择器',
    desc: '颜色选择工具',
    path: '/color',
    icon: '/color.png',
  },
  {
    title: 'UUID 生成器',
    desc: 'UUID 生成工具',
    path: '/uuid',
    icon: '/uuid.png',
  },
  {
    title: '字数统计',
    desc: '字数统计工具',
    path: '/count',
    icon: '/count.png',
  },
  {
    title: 'MD5 加密',
    desc: 'MD5 加密工具',
    path: '/lock',
    icon: '/lock.png',
  },
  {
    title: '图片压缩',
    desc: '图片压缩工具',
    path: '/zip',
    icon: '/zip.png',
  },
  {
    title: 'Markdown 编辑器',
    desc: 'Markdown 在线编辑器',
    path: '/markdown',
    icon: '/markdown.png',
  },
  {
    title: 'favicon 制作',
    desc: 'favicon 制作工具',
    path: '/favicon',
    icon: '/favicon.png',
  },
  {
    title: 'IP 地址查询',
    desc: 'IP 归属地查询工具',
    path: '/ip',
    icon: '/ip.png',
  },
];
